In [1]:
'''
The things you always forget about linear algebra both notation wise and implementation wise

Covers:
PARAMETRIC FORMS
TRACE
INVERSE
RANK
MATRIX MULTIPLACATION
DOT PRODUCT
ORTHOGONALITY
UNIT VECTOR
ORTHOGONAL COMPLEMENT

# Best Reference Found: http://textbooks.math.gatech.edu/ila/

'''

'\nThe things you always forget about linear algebra both notation wise and implementation wise\n'

In [ ]:
'''
A system of equations that has infinitely many solutions due to the reduced form containing a variable is written
in PARAMETRIC FORM - this solution set describes a plane.

Example:
x = 1 - 5z
y = -1 - 2z
z = z

Recipe: Parametric form
The parametric form of the solution set of a consistent system of linear equations is obtained as follows.

Write the system as an augmented matrix.
Row reduce to reduced row echelon form.
Write the corresponding (solved) system of linear equations.
Move all free variables to the right hand side of the equations.
From: https://textbooks.math.gatech.edu/ila/parametric-form.html
'''

In [2]:
# Trace - the Sum of elements on the diagonal
import numpy as np
identity_five = np.identity(5)
identity_five.trace() # i.e. for Identity matrix, always the size of the matrix

5.0

In [15]:
# Inverse - the matrix B that when multiple by A gives Identity matrix I
from numpy.linalg import inv, matrix_rank
s = np.arange(16).reshape((4,4)) * 4
inv(s)

array([[ 2.25179981e+14, -1.12589991e+14, -4.50359963e+14,
         3.37769972e+14],
       [-6.00479950e+14,  6.75539944e+14,  4.50359963e+14,
        -5.25419957e+14],
       [ 5.25419957e+14, -1.01330992e+15,  4.50359963e+14,
         3.75299969e+13],
       [-1.50119988e+14,  4.50359963e+14, -4.50359963e+14,
         1.50119988e+14]])

In [16]:
# Rank - the number of linearly independent columns of the Matrix - note that row rank and column rank are always equal
matrix_rank(s)

2

In [19]:
'''
The dot product multiplies two vectors and returns a scalar
x * y = x[1]y[1] + x[2]y[2] + x[n]y[n]

The dot product is commutative: x * y = y * x
Distributive with addition: (x + y) * z = x * z + y * z
Distributive with scalar multiplacation: (c * x)  * y = c * (x * y)
'''
dot = np.dot([1,2,3], [4,5,6])
# 1*4 + 2 * 5 + 3 * 6
dot

32

In [22]:
import math
# The length of a vector is the square root of its dot product with itself
# ||x|| = sqrt(x*x)
x = [3,4]
vector_length = math.sqrt(np.dot(x,x))
vector_length

5.0

In [ ]:
# Multiplication - by Scalar, Vector, Matrix
# Ref: https://www.mathsisfun.com/algebra/matrix-multiplying.html
# When multiplying two matrices, you get as many rows as the 1st term and as many columns as the 2nd term


In [35]:
'''
The property defining the closest point between a subspace (plane) and a given point is that the vector between the
two is orthogonal (perpendicular) to the subspace. Therefore the search for the orthogonal vector is a search over
the space that minimizes the distance.

The distance between two points is the *length* of the vector between them
'''
a = [4, 5]
b = [7, 10]
vect_dist = np.subtract(b, a)
math.sqrt(np.dot(vect_dist, vect_dist)) 

5.830951894845301

In [32]:
'''
The UNIT VECTOR is a vector with length 1. There are infinitely many per definition of legnth, but 
[1, 0, 0], [0, 1, 0], [0, 0, 1] are the unit vectors defining 3D space

For any nonzero vector x, there is one unit vector pointing in the same direction. It is obtained by dividing 
the x by the length of x
'''
unit_vect = vect_dist / (math.sqrt(np.dot(vect_dist, vect_dist)))
unit_vect

array([0.51449576, 0.85749293])

In [33]:
(math.sqrt(np.dot(unit_vect, unit_vect)))

0.9999999999999999

In [ ]:
'''
Vectors are orthogonal iff their dot product is 0
Notation: x ⊥ y if x • y = 0

ORTHOGONAL COMPLEMENT: The Orthogonal Complement of subspace W is the set {v in R^n where v • w = 0 for w in W}
ORTHOGONAL PROJECTION: The vector from subspace W to point x: key formula is
Projection Vector xL = (u • x / u • u) * u,
where u is a line on W closest to x and x is a point
'''

In [5]:
s = np.array([9.52551809, 0.51430058])
np.diag(s) # Turn a vector into a diagonal matrix

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [ ]:
'''
Next up: Linear transformations: https://textbooks.math.gatech.edu/ila/chap-matrices.html
'''