In [2]:
'''
The things you always forget about linear algebra both notation wise and implementation wise

Covers:
PARAMETRIC FORMS
TRACE
INVERSE
RANK
NORMS
MATRIX MULTIPLACATION
DOT PRODUCT
ORTHOGONALITY
UNIT VECTOR
ORTHOGONAL COMPLEMENT
POSITIVE SEMI-DEFINITE
QUADRATIC FUNCTION
SINGULAR VALUES
THE MATRIX EQUATION: Ax = b FORM

# Best Reference Found: http://textbooks.math.gatech.edu/ila/

'''

'\nThe things you always forget about linear algebra both notation wise and implementation wise\n\nCovers:\nPARAMETRIC FORMS\nTRACE\nINVERSE\nRANK\nNORMS\nMATRIX MULTIPLACATION\nDOT PRODUCT\nORTHOGONALITY\nUNIT VECTOR\nORTHOGONAL COMPLEMENT\nPOSITIVE SEMI-DEFINITE\nQUADRATIC FUNCTION\nSINGULAR VALUES\nTHE MATRIX EQUATION: Ax = b FORM\n\n# Best Reference Found: http://textbooks.math.gatech.edu/ila/\n\n'

In [3]:
from numpy.linalg import inv, matrix_rank
import numpy as np

In [4]:
'''
A system of equations that has infinitely many solutions due to the reduced form containing a variable is written
in PARAMETRIC FORM - this solution set describes a plane.

Example:
x = 1 - 5z
y = -1 - 2z
z = z

Recipe: Parametric form
The parametric form of the solution set of a consistent system of linear equations is obtained as follows.

Write the system as an augmented matrix.
Row reduce to reduced row echelon form.
Write the corresponding (solved) system of linear equations.
Move all free variables to the right hand side of the equations.
From: https://textbooks.math.gatech.edu/ila/parametric-form.html
'''

'\nA system of equations that has infinitely many solutions due to the reduced form containing a variable is written\nin PARAMETRIC FORM - this solution set describes a plane.\n\nExample:\nx = 1 - 5z\ny = -1 - 2z\nz = z\n\nRecipe: Parametric form\nThe parametric form of the solution set of a consistent system of linear equations is obtained as follows.\n\nWrite the system as an augmented matrix.\nRow reduce to reduced row echelon form.\nWrite the corresponding (solved) system of linear equations.\nMove all free variables to the right hand side of the equations.\nFrom: https://textbooks.math.gatech.edu/ila/parametric-form.html\n'

# Trace
* The Sum of the elements on the diagonal of the matrix
* A kinda dumb identity shown below - for the identity matrix, the trace is always the size of m (or n) in the matrix

In [5]:
identity_five = np.identity(5)
identity_five.trace() # i.e. for Identity matrix, always the size of the matrix

5.0

In [6]:
# Inverse - the matrix B that when multiple by A gives Identity matrix I
s = np.arange(16).reshape((4,4)) * 4
inv(s)

array([[ 2.25179981e+14, -1.12589991e+14, -4.50359963e+14,
         3.37769972e+14],
       [-6.00479950e+14,  6.75539944e+14,  4.50359963e+14,
        -5.25419957e+14],
       [ 5.25419957e+14, -1.01330992e+15,  4.50359963e+14,
         3.75299969e+13],
       [-1.50119988e+14,  4.50359963e+14, -4.50359963e+14,
         1.50119988e+14]])

# Rank
The number of **linearly independent columns** of the Matrix (meaning remaining non-zero columns when in row echelon form post Gaussian elimination) - note that **row rank and column rank are always equal**

In [7]:
matrix_rank(s)

2

# Norms
* A Norm is the **total length of all vectors in a space**

## $\displaystyle{ \ell_{0} }$ Norm
*Not a real norm, equivalent to the count of nonzero vectors in the space. e.g. {[0,0][0,2]} has an L0 norm of 1
##  $\displaystyle{ \ell_{1} }$ Norm
* Taxicab distance - The **sum of magnitudes in the vector space**
* e.g. from origin to [3,4]: $\displaystyle{ ||X||_{1} = |3| + |4| = 7 }$

##  $\displaystyle{ \ell_{2} }$ Norm
* The shortest distance from the origin to go from one to the other - it becomes the hypoteneuse of the triangle formed by these three lines
* Because of this Pythagorean theorem gives this norm: $\displaystyle{ ||X||_{2} = \sqrt{|3|^2 + |4|^2} = \sqrt{25} = 5}$

In [8]:
'''
The dot product multiplies two vectors and returns a scalar
x * y = x[1]y[1] + x[2]y[2] + x[n]y[n]

The dot product is commutative: x * y = y * x
Distributive with addition: (x + y) * z = x * z + y * z
Distributive with scalar multiplacation: (c * x)  * y = c * (x * y)

This is an example (but not the only) inner product space
'''
dot = np.dot([1,2,3], [4,5,6])
# 1*4 + 2 * 5 + 3 * 6
dot

32

In [9]:
import math
# The length of a vector is the square root of its dot product with itself
# ||x|| = sqrt(x*x)
x = [3,4]
vector_length = math.sqrt(np.dot(x,x))
vector_length

5.0

In [10]:
# Multiplication - by Scalar, Vector, Matrix
# Ref: https://www.mathsisfun.com/algebra/matrix-multiplying.html
# When multiplying two matrices, you get as many rows as the 1st term and as many columns as the 2nd term


In [11]:
'''
The property defining the closest point between a subspace (plane) and a given point is that the vector between the
two is orthogonal (perpendicular) to the subspace. Therefore the search for the orthogonal vector is a search over
the space that minimizes the distance.

The distance between two points is the *length* of the vector between them
'''
a = [4, 5]
b = [7, 10]
vect_dist = np.subtract(b, a)
math.sqrt(np.dot(vect_dist, vect_dist)) 

5.830951894845301

In [12]:
'''
The UNIT VECTOR is a vector with length 1. There are infinitely many per definition of legnth, but 
[1, 0, 0], [0, 1, 0], [0, 0, 1] are the unit vectors defining 3D space

For any nonzero vector x, there is one unit vector pointing in the same direction. It is obtained by dividing 
the x by the length of x
'''
unit_vect = vect_dist / (math.sqrt(np.dot(vect_dist, vect_dist)))
unit_vect

array([0.51449576, 0.85749293])

In [13]:
(math.sqrt(np.dot(unit_vect, unit_vect)))

0.9999999999999999

In [14]:
'''
Vectors are orthogonal iff their dot product is 0
Notation: x ⊥ y if x • y = 0

ORTHOGONAL COMPLEMENT: The Orthogonal Complement of subspace W is the set {v in R^n where v • w = 0 for w in W}
ORTHOGONAL PROJECTION: The vector from subspace W to point x: key formula is
Projection Vector xL = (u • x / u • u) * u,
where u is a line on W closest to x and x is a point
'''

'\nVectors are orthogonal iff their dot product is 0\nNotation: x ⊥ y if x • y = 0\n\nORTHOGONAL COMPLEMENT: The Orthogonal Complement of subspace W is the set {v in R^n where v • w = 0 for w in W}\nORTHOGONAL PROJECTION: The vector from subspace W to point x: key formula is\nProjection Vector xL = (u • x / u •\xa0u) * u,\nwhere u is a line on W closest to x and x is a point\n'

In [15]:
s = np.array([9.52551809, 0.51430058])
np.diag(s) # Turn a vector into a diagonal matrix

array([[9.52551809, 0.        ],
       [0.        , 0.51430058]])

In [16]:
'''
Next up: Linear transformations: https://textbooks.math.gatech.edu/ila/chap-matrices.html
'''

'\nNext up: Linear transformations: https://textbooks.math.gatech.edu/ila/chap-matrices.html\n'

# Positive Semidefinite
* An ${n  x  n}$ square matrix is said to be positive semi definite if the scalar output o|f ${z^T • M • z}$ is positive for all ${z}$ of size ${n}$

# Affine Function
* Function in the form of a variable + a constant - a straight line in the form $\displaystyle{mx + b}$

# Quadratic Function

* A function whose highest degree is 2.

# Singular Values
* The absolute values of the eigenvalues of a system of equations

# The Matrix Equation Ax = b
* Multiplying a matrix A times a vector x can be viewed a linear combination of the columns of A using the x as weights
* Ax - b = 0 shows up all the time in machine learning for linear problems