MATRIX DECOMPOSITION: Describe a matrix using its constituent elements. The most widely used decomposition is SINGULAR VALUE DECOMPOSITION (SVD). 
* All matrices have an SVD. 
* A matrix can be reconstructed using the constituent elements with the dot product: U • S • V^T
* Dimensionality reduction can be performed with SVD
* The pseudoinverse can be computed with SVD
* Calculated with iterative numerical methods
* In Python, calculated with the svd() function from scipy.linalg()

Three Elements -> A = U • Sigma • V^T

U: m x m matrix - the columns are the **left singular** values of A

Sigma: m x n diagonal matrix. The diagonal values are known as **singular values** of the original matrix

V^T: transpose of an n X n matrix. The columns are the **right singular** values of A


COLSPACE: The enumeration of columns which compose rank

ROWSPACE: The enumeration of rows which compose the rank

Sources: https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

In [3]:
import numpy as np
from scipy.linalg import svd
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
U, s, VT = svd(A) # SVD 

In [5]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [7]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [8]:
# Reconstituting original matrix from decomposition
# s is returned as a singular value vector, so we have to turn it into a diagonal matrix
Sigma = np.zeros((A.shape[0], A.shape[1])) # m x n matrix in shape of original
Sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
# Populate with nxn diagonal matrix from diagonalizing s
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [17]:
# Now we can reconstruct original matrix
B = U.dot(Sigma.dot(VT))
B # wow!

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Pseudoinver