## MATRIX DECOMPOSITION: 
* Describe a matrix using its constituent elements. The most widely used decomposition is SINGULAR VALUE DECOMPOSITION (SVD). 
* All matrices have an SVD. 
* A matrix can be reconstructed using the constituent elements with the dot product: U • S • V^T
* Dimensionality reduction can be performed with SVD
* The pseudoinverse can be computed with SVD
* Calculated with iterative numerical methods
* In Python, calculated with the svd() function from scipy.linalg()

Three Elements -> A = U • Sigma • V^T

U: m x m matrix - the columns are the **left singular** values of A

Sigma: m x n diagonal matrix. The diagonal values are known as **singular values** of the original matrix

V^T: transpose of an n X n matrix. The columns are the **right singular** values of A


COLSPACE: The enumeration of columns which compose rank

ROWSPACE: The enumeration of rows which compose the rank

Sources: https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

In [3]:
import numpy as np
from scipy.linalg import svd
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
U, s, VT = svd(A) # SVD 

In [5]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [7]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

In [8]:
# Reconstituting original matrix from decomposition
# s is returned as a singular value vector, so we have to turn it into a diagonal matrix
Sigma = np.zeros((A.shape[0], A.shape[1])) # m x n matrix in shape of original
Sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
# Populate with nxn diagonal matrix from diagonalizing s
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [17]:
# Now we can reconstruct original matrix
B = U.dot(Sigma.dot(VT))
B # wow!

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Pseudoinverse
* The **pseudoinverse** generalizes the inverse concept to non-square matrices
* Also known as the **Moore-Penrose inverse** or **Generalized inverse**
* The pseudoinverse is denoted as **A^+ = V • D^+  • U^T**, or in plain english the dot product of V (not tranposed), D^T is the pseudoinverse of the singular value matrix Sigma, and U is the tranpose of the left singular matrix.
* U and V are present in the SVD - the D^+ term comes from taking the inverse (1/n) of each nonzero value of Sigma


In [20]:
A = np.array([
 [0.1, 0.2],
 [0.3, 0.4],
 [0.5, 0.6],
 [0.7, 0.8]
])

In [21]:
B = np.linalg.pinv(A) # pseudoinverse
B

array([[-1.00000000e+01, -5.00000000e+00,  9.07607323e-15,
         5.00000000e+00],
       [ 8.50000000e+00,  4.50000000e+00,  5.00000000e-01,
        -3.50000000e+00]])

## Dimensionality Reduction
* Dimensionality reduction can be accomplished using SVD by identifying the most orthogonal features in a feature set
* This works by selecting the k largest singular values of Sigma (the feature set used in a regression)
* You can then restore the original matrix using the newly selected k values
* An application is in natural language processing - dimensionality reduction is performed on the word frequency matrix - it's called **Latent semantic analysis**

In [25]:
# Define a 3 x 10 matrix (more features than observations)
A = np.linspace(1,30, 30).reshape(3, 10)
print(A)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [28]:
U, s, VT = np.linalg.svd(A)

In [33]:
# M x n Sigma matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
# populate sigma with SVD sigma output
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

In [34]:
# How many elements to take - top 2 from original 3
n_elements = 2
Sigma = Sigma[:, :n_elements]
Sigma

array([[96.96573419,  0.        ],
       [ 0.        ,  7.25578339],
       [ 0.        ,  0.        ]])

In [36]:
VT = VT[:n_elements, :] # reshape VT to n_elements x n
VT

array([[-0.24139304, -0.25728686, -0.27318068, -0.2890745 , -0.30496832,
        -0.32086214, -0.33675595, -0.35264977, -0.36854359, -0.38443741],
       [-0.53589546, -0.42695236, -0.31800926, -0.20906617, -0.10012307,
         0.00882003,  0.11776313,  0.22670623,  0.33564933,  0.44459242]])

In [48]:
# reconstruct original matrix
B = U.dot(Sigma.dot(VT))
B # approximation returns same results
# Reduced transformation
T = U.dot(Sigma)
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [51]:
T = A.dot(VT.T) # U • Sigma === A • VT^T
T

array([[-18.52157747,   6.47697214],
       [-49.81310011,   1.91182038],
       [-81.10462276,  -2.65333138]])

In [47]:
# Scikit-learn offers a shortcut method for this
import sklearn.decomposition
svd = sklearn.decomposition.TruncatedSVD(n_components=2)
svd.fit(A) # fit this decomposition to original matrix
result = svd.transform(A) # Transform this matrix to SVD
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
